/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jo.edu.bau.pay;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import jo.edu.bau.settings.ThemeManager;
import jo.edu.bau.utils.DatabaseConnection;


/**
 *
 * @author User
 */
public class Payroll extends javax.swing.JPanel {

    /**
     * Creates new form Payment
     */
    public Payroll() {
        initComponents();
            loadPayroll(jTable1); // أضف هذا
             jButton4.setBackground(new java.awt.Color(30, 100, 200));
    jButton4.setForeground(java.awt.Color.WHITE);
    jButton4.setOpaque(true);
 this.setLayout(new java.awt.BorderLayout());
    this.add(jPanel1, java.awt.BorderLayout.CENTER);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(869, 690));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Payroll");

        jTextField1.setText("🔍 Search Employee");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EMP_ID", "FIRST_NAME", "LAST_NAME", "JOB_ID", "BAIC_SALARY ", "PAY_DATE", "ALLOWNCE ", "DEDUCT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Salary details");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(538, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select an employee first", "Warning",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Payroll_Details dialog = new Payroll_Details(null, true);

String dept = "";
try {
    int empId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
    java.sql.PreparedStatement psDept = jo.edu.bau.utils.DatabaseConnection.getConnection()
        .prepareStatement("SELECT DEPARTMENT FROM EMPLOYEE WHERE EMP_ID=?");
    psDept.setInt(1, empId);
    java.sql.ResultSet rsDept = psDept.executeQuery();
    if (rsDept.next()) dept = rsDept.getString("DEPARTMENT");
    psDept.close();
} catch (Exception ex) {
    ex.printStackTrace();
}

dialog.setPayrollData(
    jTable1.getValueAt(selectedRow, 0).toString(),
    jTable1.getValueAt(selectedRow, 1).toString(),
    jTable1.getValueAt(selectedRow, 2).toString(),
    jTable1.getValueAt(selectedRow, 3).toString(),
    dept,
    jTable1.getValueAt(selectedRow, 4).toString(),
    jTable1.getValueAt(selectedRow, 6).toString(),
    jTable1.getValueAt(selectedRow, 7).toString()
);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
public void loadPayroll(javax.swing.JTable table) {
    try {
        String sql = "SELECT EMP_ID, FIRST_NAME, LAST_NAME, JOB_ID, BASIC_SALARY, PAY_DATE, ALLOWANCE, DEDUCTION FROM PAYROLL";
        PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = new DefaultTableModel(
            new String[]{"EMP_ID","First Name","Last Name","Job","Basic Salary","Pay Date","Allowance","Deduction"}, 0
        );
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("EMP_ID"), rs.getString("FIRST_NAME"),
                rs.getString("LAST_NAME"), rs.getString("JOB_ID"),
                rs.getDouble("BASIC_SALARY"), rs.getDate("PAY_DATE"),
                rs.getDouble("ALLOWANCE"), rs.getDouble("DEDUCTION")
            });
        }
        table.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

}
public void refresh() {
    loadPayroll(jTable1);
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

